export const ORDERS_GET_SUCCESS = 'ORDERS_GET_SUCCESS';
export const ORDERS_GET_FAILURE = 'ORDERS_GET_FAILURE';

export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAILURE = 'ORDER_ADD_FAILURE';

export const ORDER_EDIT_SUCCESS = 'ORDER_EDIT_SUCCESS';
export const ORDER_EDIT_FAILURE = 'ORDER_EDIT_FAILURE';

export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAILURE = 'ORDER_DELETE_FAILURE';
