// Orders

export const ORDERS_GET_LOADING = 'ORDERS_GET_LOADING';
export const ORDERS_GET_SUCCESS = 'ORDERS_GET_SUCCESS';
export const ORDERS_GET_FAILURE = 'ORDERS_GET_FAILURE';

export const ORDER_ADD_LOADING = 'ORDER_ADD_LOADING';
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAILURE = 'ORDER_ADD_FAILURE';

export const ORDER_EDIT_LOADING = 'ORDER_EDIT_LOADING';
export const ORDER_EDIT_SUCCESS = 'ORDER_EDIT_SUCCESS';
export const ORDER_EDIT_FAILURE = 'ORDER_EDIT_FAILURE';

export const ORDER_DELETE_LOADING = 'ORDER_DELETE_LOADING';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAILURE = 'ORDER_DELETE_FAILURE';

// Profile

export const PROFILE_GET_LOADING = 'PROFILE_GET_LOADING';
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS';
export const PROFILE_GET_FAILURE = 'PROFILE_GET_FAILURE';
